export const CARROT_CHAT = 'CHATLIST/CARROT_CHAT' as const;
export const CARROT_CHAT_SUCCESS = 'CHATLIST/CARROT_CHAT_SUCCESS' as const;
export const CARROT_CHAT_FAILURE = 'CHATLIST/CARROT_CHAT_FAILURE' as const;
export const GROUP_CHAT = 'CHATLIST/GROUP_CHAT' as const;
export const GROUP_CHAT_SUCCESS = 'CHATLIST/GROUP_CHAT_SUCCESS' as const;
export const GROUP_CHAT_FAILURE = 'CHATLIST/GROUP_CHAT_FAILURE' as const;
